experiments/graph_classification/real_world/benzene/benzene_gcn_pgmexplainer.sh
experiments/graph_classification/real_world/fluoride_carbonyl/fluoride_carbonyl_gcn_pgmexplainer.sh
experiments/graph_classification/real_world/mutagenicity/mutag_gcn_pgmexplainer.sh
experiments/graph_classification/synthetic/6_cycle_X_house/synth_cycle_6_house_gcn_pgmexplainer.sh
experiments/graph_classification/synthetic/bull_X_4_cycle/synth_bull_4_cycle_gcn_pgmexplainer.sh
experiments/graph_classification/synthetic/house_X_wheel/synth_house_wheel_gcn_pgmexplainer.sh
experiments/graph_classification/synthetic/wheel_X_cube/synth_wheel_cube_gcn_pgmexplainer.sh
experiments/graph_classification/synthetic/wheel_X_cube/synth_wheel_cube_gcn_grad_explainer.sh